version: '3.8'
services:
  
  db:
    image: postgres:13.0-alpine
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - ../.env
    container_name: caseme_postgres_db
  
  backend:
    # image: vadimvolkovsky/foodgram:latest
    build: ../backend
    restart: always
    # ports:
    #  - "8000:8000"
    volumes:
      - static_value:/app/backend_static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - ../.env
    container_name: caseme_web

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      # - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/backend_static/
      - media_value:/var/html/media/
    depends_on:
      - backend
    container_name: caseme_nginx


volumes:
  static_value:
  media_value: